### ISSUE TITLE
Fix CSS background in the header

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/duwamish#128]
Currently, the CSS is not loading. I believe the issue is coming from this section of our `default.css` file:

```css
#site-header {
  /*color: #eee;*/
  background: url(/images/lightpaperfibers.png);
  position: relative;
  z-index: 40;
  padding: 0.5em;
  box-shadow: 0 0.125em 0 rgba(0,0,0,0.2);
}
```

as well as this section:

```css
  /* Header */
  #site-header {
    padding-left: 1em;
    overflow: visible;
    height: 4em;  /* height of site-header */
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
    background: url(/images/lightpaperfibers.png);
  }
```

I think there is a problem with the line `url(/images/lightpaperfibers.png);`. Maybe we can try a different image, or an image url from the web, like `url(http://i724.photobucket.com/albums/ww247/druebeall/ys4w.jpg)`? 

It would be helpful to have someone test out a few different images and see what looks best. Maybe we can use a river-themed background at some point?
